# Generated by Django 6.0 on 2026-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_experiment_model_type_alter_experiment_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
